In [4]:
import pandas as pd

In [5]:
pokemon = pd.read_csv("moves.csv")
moves = pd.read_csv("pokemon.csv")
regions = pd.read_csv("regions.csv")
types = pd.read_csv("types.csv")

In [6]:
pokemon.head()

   pokemon_id  move_id pokemon_name     move_name
0           1       13    bulbasaur    razor-wind
1           1       14    bulbasaur  swords-dance
2           1       15    bulbasaur           cut
3           1       20    bulbasaur          bind
4           1       22    bulbasaur     vine-whip

In [7]:
moves.head()

,id,name,base_experience,height,weight,hp,attack,defense,special-attack,special-defense,speed,is_baby,is_mythical,is_legendary
0,1,bulbasaur,64.0,7,69,45,49,49,65,65,45,False,False,False
1,2,ivysaur,142.0,10,130,60,62,63,80,80,60,False,False,False
2,3,venusaur,236.0,20,1000,80,82,83,100,100,80,False,False,False
3,4,charmander,62.0,6,85,39,52,43,60,50,65,False,False,False
4,5,charmeleon,142.0,11,190,58,64,58,80,65,80,False,False,False

In [8]:
types.head()

   pokemon_id  type_id pokemon_name type_name
0           1       12    bulbasaur     grass
1           1        4    bulbasaur    poison
2           2       12      ivysaur     grass
3           2        4      ivysaur    poison
4           3       12     venusaur     grass

In [9]:
regions.head()

   pokemon_id  region_id pokemon_name      region_name
0           1         31    bulbasaur  lets-go-pikachu
1           1          3    bulbasaur           yellow
2           1          1    bulbasaur              red
3           1         15    bulbasaur        heartgold
4           1         23    bulbasaur                x